# Site settings
title: Ariescat Blog
SEOTitle: 一只白羊座的傻猫 | Ariescat Blog
header-img: img/cover/166801.jpg
email: 1275563227@qq.com
description: "一个在互联网苟且偷生的工具人 @Ariescat"
keyword: "一只白羊座的傻猫, Blog, Java, Ariescat"
url: "https://ariescat.top/"                # your host, for absolute URL
baseurl: ""                                 # for example, '/blog' if your blog hosted on 'host/blog'
picurl: ""                                  # 图床地址
github_repo: "blog"

# Sidebar settings
sidebar: true                               # whether or not using Sidebar.
sidebar-about-description: "不管这一天有多难过，记得认真洗脸冲澡..."
sidebar-avatar: /img/avatar.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    Ariescat
jianshu_username:   39035eb3096b
csdn_username:      PingXiaoGai
gitbook_url:        https://awesome.ariescat.top/
#weibo_username:
#zhihu_username:
#facebook_username:
#twitter_username:




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude:
  - less
  - node_modules
  - bin
  - vendor
  - Gruntfile.js
  - package.json
  - README.md
  - CNAME
  - Gemfile*
anchorjs: true                  # if you want to customize anchor. check out line:181 of `post.html`
collections:
  docs:
    output: true


# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                    # use Github Flavored Markdown !important



# 评论系统

# Gitalk
gitalk:
  enable: false                  #是否开启Gitalk评论
  clientID: 1b762e3fb7d766fefa60                            #生成的clientID
  clientSecret: c011a01671ccb88ba8640c4e488014b12ca41cbf    #生成的clientSecret
  repo: ariescat.github.io      #仓库名称
  owner: ariescat               #github用户名
  admin: ariescat
  distractionFreeMode: true     #是否启用类似FB的阴影遮罩

# Valine
valine:
  enable: true                  #是否开启Valine评论
  appId: 8sgcuqXs6ecrgY74WuVkQXCJ-gzGzoHsz                  #生成的appId
  appKey: QXoMCzb8TFMV0DBzDNXkcvxa                          #生成的appKey
  serverURL: https://api.comment.ariescat.top
  placeholder: '你是我一生只会遇见一次的惊喜 | ᴥ•́ )✧'    #评论框占位提示符
  enableQQ: true                #是否启用昵称框自动获取QQ昵称和QQ头像
  recordIP: true                #是否记录评论者IP

# Twikoo
twikoo:
  enable: false
  envId: blog-5gkhnwtme934ae46  # CloudBase的环境id

# Waline
waline:
  enable: false
  serverURL: https://blog-waline-one.vercel.app/
  placeholder: '你是我一生只会遇见一次的惊喜 ...'


# Aplayer
aplayer:
  enable: true


# Artitalk
artitalk:
  enable: true



# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 15a0182bcc909fead8c8f48acb3222d4

# Google Analytics
ga_track_id: G-HPNE1L0HRN



# Featured Tags
featured-tags: true             # 是否使用首页标签
featured-condition-size: 0      # 相同标签数量大于这个数，才会出现在首页，默认为0



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Links
links:
  - title: "简书"
    href: "https://www.jianshu.com/"
  - title: "知乎"
    href: "https://www.zhihu.com/"
  - title: "掘金"
    href: "https://juejin.im/"