name: deploy-coding

on:
  push:
    branches:
      - main  # Here source code branch is `master`, it could be other branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12.18.2

      - name: Run npm install github-gh
        run: |
          echo '{"scripts": {"gh-pages-dev": "gh-pages"},"devDependencies": {"gh-pages": "^3.2.3"}}' > package.json
          npm install

      - name: Run echo github-gh
        run: echo `npm run gh-pages-dev -- -V`

      - name: Setup Ruby, JRuby and TruffleRuby
        # You may pin to the exact commit or the version.
        # uses: ruby/setup-ruby@57d46d78b7d959dc4a248024a29bb17d4e357e5c
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Run bundle install
        run: bundle install

      - name: Run echo jekyll
        run: echo `bundle exec jekyll -v`

      - name: Run jekyll build
        run: bundle exec jekyll build

      - name: Run module gh-pages
        run: npm run gh-pages-dev -- -d _site -b temp-page -r 'https://${{secrets.USER_TOKEN}}@github.com/Ariescat/blog.git' -u 'github-actions-bot <${{secrets.EMAIL}}>' -m 'github-actions-bot Updates'

      # - name: Run deploy-coding-master
        # 用户名密码中一定要转义 @符号 转码后变成了%40  See:https://blog.csdn.net/u012447791/article/details/118225605
        # eg. https://username:password@127.0.0.1/res/res.git
        # 弃用coding 2021年12月25日
        # run: npm run gh-pages-dev -- -d _site -b master -r "${{secrets.CODING_URL}}" -u "github-actions-bot <${{secrets.EMAIL}}>" -m "github-actions-bot Updates"
